
    create table tb_attachment (
        binary_id integer,
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_binary (
        id integer generated by default as identity,
        bytes varbinary(255),
        primary key (id)
    );

    create table tb_category (
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_comment (
        id integer generated by default as identity,
        post_id integer,
        user_id integer,
        date timestamp(6),
        text varchar(255),
        primary key (id)
    );

    create table tb_like (
        comment_id integer,
        id integer generated by default as identity,
        post_id integer,
        user_id integer,
        primary key (id)
    );

    create table tb_notification (
        id integer generated by default as identity,
        is_read boolean,
        user_id integer,
        date timestamp(6),
        text varchar(255),
        primary key (id)
    );

    create table tb_post (
        category_id integer,
        id integer generated by default as identity,
        is_urgent boolean,
        status integer,
        user_id integer,
        date timestamp(6),
        description varchar(255),
        title varchar(255),
        primary key (id)
    );

    create table tb_post_attachment (
        attachment_id integer,
        id integer generated by default as identity,
        post_id integer unique,
        primary key (id)
    );

    create table tb_role (
        id integer generated by default as identity,
        authority varchar(255),
        primary key (id)
    );

    create table tb_user (
        id integer generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table tb_user_attachment (
        attachment_id integer,
        id integer generated by default as identity,
        user_id integer unique,
        primary key (id)
    );

    create table tb_user_role (
        role_id integer not null,
        user_id integer not null,
        primary key (role_id, user_id)
    );

    alter table if exists tb_attachment 
       add constraint FK3qqopk5n4umrg7cqge2qv05la 
       foreign key (binary_id) 
       references tb_binary;

    alter table if exists tb_comment 
       add constraint FKebak8c8m45519djplq0wanuj3 
       foreign key (post_id) 
       references tb_post;

    alter table if exists tb_comment 
       add constraint FK45c1cuqlljd60ihc9j0962ekq 
       foreign key (user_id) 
       references tb_user;

    alter table if exists tb_like 
       add constraint FK8683wycpmayvsvityxd81a5l4 
       foreign key (comment_id) 
       references tb_comment;

    alter table if exists tb_like 
       add constraint FKa898t472uhrnm5jcoaa7aa0us 
       foreign key (post_id) 
       references tb_post;

    alter table if exists tb_like 
       add constraint FK245qh9w9lju2652at7qisf9rt 
       foreign key (user_id) 
       references tb_user;

    alter table if exists tb_notification 
       add constraint FK9ihj3k9lv33u6qd10wq18f482 
       foreign key (user_id) 
       references tb_user;

    alter table if exists tb_post 
       add constraint FKhx7a7k3pf66vpddqg5pr12anw 
       foreign key (user_id) 
       references tb_user;

    alter table if exists tb_post 
       add constraint FKt2nx86qhg2vs9hp2k5hdshx9t 
       foreign key (category_id) 
       references tb_category;

    alter table if exists tb_post_attachment 
       add constraint FKgljicrmovitq1efn1qccmksk3 
       foreign key (attachment_id) 
       references tb_attachment;

    alter table if exists tb_post_attachment 
       add constraint FKfhhtcoefk6l50e9138kgeth2a 
       foreign key (post_id) 
       references tb_post;

    alter table if exists tb_user_attachment 
       add constraint FK7m0bf4i39swe12sixuftr09nm 
       foreign key (attachment_id) 
       references tb_attachment;

    alter table if exists tb_user_attachment 
       add constraint FK14w1wsodhcbpotffmthjvrca6 
       foreign key (user_id) 
       references tb_user;

    alter table if exists tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table if exists tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;
INSERT INTO tb_user (name, email, password) VALUES ('Alex', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_CITIZEN');
INSERT INTO tb_role (authority) VALUES ('ROLE_ANALYST');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 3);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);
